### ISSUE TITLE
3 Error when try to compiling the code under Mac os 

### ISSUE THREAD

**Issue by gfm-r** [ColumPaget/Hashrat#12]
Here is an screenshot of the errors

![screen shot 2019-01-15 at 6 14 08 pm](https://user-images.githubusercontent.com/34504649/51189586-69a33780-18f1-11e9-99c5-1f6899b08c9c.png)

**Comment by ColumPaget** [comment]
Thanks for reporting these, I'll look into them.

**Comment by ColumPaget** [comment]
Fixed in version 1.10.3. Sorry for the long, long wait for this!
