### ISSUE TITLE
[Feature Request] Verbose mode

### ISSUE THREAD

**Issue by JKamsker** [ColumPaget/Hashrat#13]
Hey, 
I'd like to see more output what the program does. 
Specifically, I'd like to know how long hashing a file takes in comparison to other algorithms.
The preferred output format would be in milliseconds

Thank you!

**Comment by ColumPaget** [comment]
That's a cool idea, I'll look into doing that.

Colum

**Comment by ColumPaget** [comment]
Done in version 1.10.3. running hashrat with -v option adds a 'hash-time' value to the output, so long as you're using standard hashrat format output.
