### ISSUE TITLE
Zlib support reported as enabled when --enable-ssl is but --enable-zlib is NOT given

### ISSUE THREAD

**Issue by MarcusRoeckrath** [ColumPaget/Hashrat#14]
On configure it is reported:

############# libUseful Build Config: #############
Largefiles ( > 2GB ) NOT enabled
Filesystem attribues (xattr) NOT enabled
Linux sendfile syscall NOT enabled
IPv6 NOT enabled
SSL/TLS enabled
zlib support enabled
linux namespace support NOT enabled
linux capabilities support NOT enabled

But I do not see that zlib is enabled in the following make run. Which would be correct because enable-zlib is not given.

So the configure report seams to be wrong.

On the other hand I do not understand the "if" line in line 4227 of libUseful-4/configure:

if test "$cf_use_zlib" = "yes" -o "$cf_use_ssl" = "yes"

At this time --enable-ssl is not evaluated and therefor cf_use_ssl not set. If cf_use_ssl would be set before but cf_use_zlib (enable-zlib not used) is not the script will try to detect zlib while this is not wanted by the user.

Why are enable-ssl and enable-zlib connected to each other? Why should enable-ssl implement a check for zlib?

**Comment by ColumPaget** [comment]
Hi Marcus,

The pandemic has given me some time to look into things! In this case zlib is, I believe, a dependancy for openssl (or was when I wrote the makefile). Thus, if you enable ssl, you enable zlib too.

Your compile failure if you use --enable-zlib is a real issue though. I'll get onto that shortly.
