### ISSUE TITLE
Unable to compile while enable-zlib is given

### ISSUE THREAD

**Issue by MarcusRoeckrath** [ColumPaget/Hashrat#15]
Configuring with --enable-zlib reports:

=== configuring in libUseful-4 (/root/tmp/Hashrat-1.10.4/libUseful-4)
configure: running /bin/sh ./configure --disable-option-checking '--prefix=/usr/local'  '--enable-zlib' 'CFLAGS=-O2 -g -m64 -fmessage-length=0 -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables' --cache-file=/dev/null --srcdir=.
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether make sets $(MAKE)... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for ptsname_r in -lc... yes
checking for clearenv in -lc... yes
checking for setresuid in -lc... yes
checking for get_current_dir_name in -lc... yes
checking for umount2 in -lc... yes
checking for umount in -lc... yes
checking for mkostemp in -lc... yes
checking for poll in -lc... yes
checking for deflate in -lz... yes
configure: creating ./config.status
config.status: creating Makefile

############# libUseful Build Config: #############
Largefiles ( > 2GB ) NOT enabled
Filesystem attribues (xattr) NOT enabled
Linux sendfile syscall NOT enabled
IPv6 NOT enabled
SSL/TLS NOT enabled
zlib support enabled
linux namespace support NOT enabled
linux capabilities support NOT enabled

Now running make fails:

libUseful-4/libUseful.a(Compression.o): In function `zlibProcessorWrite':
/root/tmp/Hashrat-1.10.4/libUseful-4/Compression.c:50: undefined reference to `deflate'
/root/tmp/Hashrat-1.10.4/libUseful-4/Compression.c:49: undefined reference to `deflate'
libUseful-4/libUseful.a(Compression.o): In function `zlibProcessorRead':
/root/tmp/Hashrat-1.10.4/libUseful-4/Compression.c:98: undefined reference to `inflate'
/root/tmp/Hashrat-1.10.4/libUseful-4/Compression.c:97: undefined reference to `inflate'
/root/tmp/Hashrat-1.10.4/libUseful-4/Compression.c:106: undefined reference to `inflateSync'
libUseful-4/libUseful.a(Compression.o): In function `zlibProcessorClose':
/root/tmp/Hashrat-1.10.4/libUseful-4/Compression.c:143: undefined reference to `inflateEnd'
/root/tmp/Hashrat-1.10.4/libUseful-4/Compression.c:144: undefined reference to `deflateEnd'
libUseful-4/libUseful.a(Compression.o): In function `zlibProcessorInit':
/root/tmp/Hashrat-1.10.4/libUseful-4/Compression.c:189: undefined reference to `inflateInit_'
/root/tmp/Hashrat-1.10.4/libUseful-4/Compression.c:194: undefined reference to `deflateInit_'
/root/tmp/Hashrat-1.10.4/libUseful-4/Compression.c:188: undefined reference to `inflateInit2_'
/root/tmp/Hashrat-1.10.4/libUseful-4/Compression.c:193: undefined reference to `deflateInit2_'
collect2: error: ld returned 1 exit status
Makefile:15: recipe for target 'hashrat' failed
make: *** [hashrat] Error 1

zlib 1.2.11 from zlib.net is used on the system.

**Comment by ColumPaget** [comment]
Sorry Marcus, somehow I never saw this issue or forgot about it. Anyways, this is fixed now in hashrat v1.20.

Thanks for reporting it.
