### ISSUE TITLE
Is the outputting of new files with -C implemented?

### ISSUE THREAD

**Issue by 8BitAce** [ColumPaget/Hashrat#20]
Hello,

I really liked the docs mention of being able to output new files not in a list of hashsums with `cat some-dir.md5 | hashrat -C -md5 ~/some-dir`. However I can't seem to get it to work. I took a quick glance through the code and I don't _think_ I see any such functionality. Is this something that's still in the works? If not, I can try to craft a list of reproduce steps.

**Comment by ColumPaget** [comment]
Hi Ace,

I'm not sure that this was the intended functionality, but even if it wasn't it's a good idea. Give me a week or so to look into this and I should be able to add/fix this functionality.

Colum

**Comment by ColumPaget** [comment]
Hi Ace,

If you check the recently released v1.15, I'll think you'll find this is fixed now. Thanks for reporting this, I found another weird bug while looking into this one too!

Colum

**Comment by 8BitAce** [comment]
Hi Colum,

Thank you for implementing this so quickly! I just gave the latest version a test, and this feature works perfectly now!

Thanks again!
