### ISSUE TITLE
"-c -xattr" didn't work properly

### ISSUE THREAD

**Issue by ttonin33** [ColumPaget/Hashrat#21]
My problem is that when using "-xattr -c" the files are not checked, so there is no info for wrong or right hash. Only for missing hash. However, this works if I read the hash from a file with "cat" and do not use "xattr".

<pre><font color="#4CE64C"><b>superuser@HP-Pc</b></font>:<font color="#295FCC"><b>~/Downloads</b></font>$ hashrat test_datei &gt; hash 
<font color="#4CE64C"><b>superuser@HP-Pc</b></font>:<font color="#295FCC"><b>~/Downloads</b></font>$ hashrat test_xattr -xattr
hash=&apos;md5:ea04f6caebb753c40a88de3541f06340&apos; type=&apos;file&apos; mode=&apos;100664&apos; uid=&apos;1000&apos; gid=&apos;1000&apos; size=&apos;9&apos; mtime=&apos;1643653735&apos; inode=&apos;23072641&apos; path=&apos;test_xattr&apos;
<font color="#4CE64C"><b>superuser@HP-Pc</b></font>:<font color="#295FCC"><b>~/Downloads</b></font>$ 
<font color="#4CE64C"><b>superuser@HP-Pc</b></font>:<font color="#295FCC"><b>~/Downloads</b></font>$ cat hash | hashrat -c *
test_datei: OKAY

Checked 1 files. 0 Failures
<font color="#4CE64C"><b>superuser@HP-Pc</b></font>:<font color="#295FCC"><b>~/Downloads</b></font>$ hashrat * -c -xattr
ERROR: No stored hash for &apos;hash&apos;
ERROR: No stored hash for &apos;test_datei&apos;
</pre>

**Comment by ColumPaget** [comment]
Hi ttonin,

thanks for reporting this. I beleive this is fixed in version 1.15 now. There was a confused 'if' statement that had a code path that could go through without printing out the results!
