### ISSUE TITLE
How does one invoke -hmac?

### ISSUE THREAD

**Issue by lewisbrown** [ColumPaget/Hashrat#26]
I want to run hmac sha256 with a key upon a string. I've tried dozens of command line syntaxes to no avail. What is the secret, please? :pray:

**Comment by ColumPaget** [comment]
Hi Lewis,

it should just be 'hashrat -sha256 -hmac [key]', but there's a couple of things that might be relevant.

1) There's old versions of libUseful where hmac didn't work. With these you'll get the debug message:

DEBUG: HashInit Hash.c:100 Unsupported Hash Type: 'hmac-sha256'.

2) Others have reported that sha hashing doesn't work for them. I've been unable to reproduce this, but it's come from a reliable source. If you run 'make check' in the hashrat source code directory, it should go through a list of checks. The third set of check is "Testing HMAC digests". What do you see there?

Colum

**Comment by lewisbrown** [comment]
Thank you. I was getting that error:

`DEBUG: HashInit Hash.c:100 Unsupported Hash Type: 'hmac-sha256'.`

Updated libUseful to current release and it works.

Why is Hashrat still using an old/broken libUseful?

**Comment by ColumPaget** [comment]
I suspect that I've been using it against my installed libUseful, which tends to be the latest version, and thus haven't realized it's shipping with an outdated version!

I'll investigate, maybe there'll be a new release.
