### ISSUE TITLE
HMAC Segmentation fault

### ISSUE THREAD

**Issue by masarlabs** [ColumPaget/Hashrat#3]
Hi,
i'm trying to use the HMAC function but it does not work:
   > echo "x" | ./hashrat -hmac a
   Segmentation fault
   > echo "x" | ./hashrat -hmac a -sha256
   Segmentation fault
   > ./hashrat --version
   version: 1.8.9

**Comment by ColumPaget** [comment]
It's been a long journey, but hmac functions are finally fixed! Thanks for reporting this!
