### ISSUE TITLE
No escaping of file names with "'" when calling hook script

### ISSUE THREAD

**Issue by sth** [ColumPaget/Hashrat#5]
When hook scripts are called, no escaping of `'` in file names is done. This will cause the `system()` call to fail or execute unexpected commands, depending on the file name:

https://github.com/ColumPaget/Hashrat/blob/bb16a5fb375a90002b3fa6e1160041819415155b/common.c#L150-L151

**Comment by ColumPaget** [comment]
Good call. Ironically libUseful has a function (Spawn) that handles that automatically, but for some reason I went and used 'system'. Gonna be issues with ';' and '|' too.  I'm due to return to doing some work on hashrat soon, so it'll be fixed in the next release.

Thanks,

Colum

**Comment by ColumPaget** [comment]
Should be fixed as of 1.8.10

Wow, this was *painful* to fix. Spent ages fighting with shell trying to escape a quote that's being passed via the "/bin/sh -c" method. Eventually concluded it couldn't be done. Switched to spawning off a /bin/sh using a pipe and writing commands to it. That now seems to work.

Thanks again for reporting it

Colum
