### ISSUE TITLE
Feature Request: Return exit code of zero (0) when hashing a file.

### ISSUE THREAD

**Issue by rwhalb** [ColumPaget/Hashrat#6]
Currently hashrat returns a exit code of one (1) when it hashes a file.

Example text file: "/tmp/abc.txt".

[root@nst26-mp tmp]# cat /tmp/abc.txt;
1234
[root@nst26-mp tmp]# hashrat /tmp/abc.txt;
hash='md5:e7df7cd2ca07f4f1ab415d457a6e1c13' type='file' mode='100644' uid='0' gid='0' size='5' mtime='1509535863' inode='38017' path='/tmp/abc.txt'
[root@nst26-mp tmp]# echo $?
1
[root@nst26-mp tmp]# 

Request: For a successful completed hash return a zero (0) exit code (POSIX standard convention), otherwise any exit code greater that zero (1) signals an error condition.

Thanks for your code contribution and consideration.

**Comment by ColumPaget** [comment]
This one should be working in the latest release!
