### ISSUE TITLE
[HELPWANTED] Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [ColumPaget/Hashrat#7]
Dear Mr. Paget,
Could you be so kind to generate ```.exe``` for the rest of us who are mere Windows users w/o compiler?

**Comment by ColumPaget** [comment]
Alas, I really don't know how to do that. I think I'd have to get a copy of windows and probably Visual C (I've been linux-only for over a decade). I'm not even sure one *can* generate a binary from the hashrat source, surely windows isn't POSIX compatible?

So unfortunately I'm afraid I can't really provide this :-(
